import React from 'react';
import { Box, Text } from 'gestalt';

export default function Discussions() {
  return (
    <Box marginTop={2} padding={5}>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
      <Text>Discussions</Text>
    </Box>
  );
}
